inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  ParserEngine: parser_prism
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'log/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

FactoryBot/ExcessiveCreateList:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - head
    - raise
    - render
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent
