defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  host: <%= ENV['POSTGRES_HOST'] || '0.0.0.0' %>
  username: fullapp
  password: fullapp
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *defaults
    database: fullapp-development
  queue:
    <<: *defaults
    database: fullapp-development-queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *defaults
    database: fullapp-production
  queue:
    <<: *defaults
    database: fullapp-production-queue
    migrations_paths: db/queue_migrate

test:
  <<: *defaults
  database: fullapp-test
