default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  host: <%= ENV['POSTGRES_HOST'] || '0.0.0.0' %>
  username: fullapp
  password: fullapp
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: fullapp_development
  cache:
    <<: *default
    database: fullapp_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: fullapp_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: fullapp_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: fullapp_test

production:
  primary:
    <<: *default
    database: fullapp_production
  cache:
    <<: *default
    database: fullapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: fullapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: fullapp_production_cable
    migrations_paths: db/cable_migrate
