name: CI

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_DB: fullapp_test
          POSTGRES_USER: fullapp
          POSTGRES_PASSWORD: fullapp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Cache Rubygems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Rubygems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.OS }}-bun-
      - name: Install Node Modules
        run: yarn install

      - name: Run Rubocop
        run: bundle exec rubocop

  specs:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_DB: fullapp_test
          POSTGRES_USER: fullapp
          POSTGRES_PASSWORD: fullapp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Cache Rubygems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Rubygems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.OS }}-bun-
      - name: Install Node Modules
        run: yarn install

      - name: Run Specs
        run: bundle exec rspec
